package tom.community.model;

public class Feed {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.id
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.gmt_create
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.user_id
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.data
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.type
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.id
     *
     * @return the value of feed.id
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.id
     *
     * @param id the value for feed.id
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.gmt_create
     *
     * @return the value of feed.gmt_create
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.gmt_create
     *
     * @param gmtCreate the value for feed.gmt_create
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.user_id
     *
     * @return the value of feed.user_id
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.user_id
     *
     * @param userId the value for feed.user_id
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.data
     *
     * @return the value of feed.data
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.data
     *
     * @param data the value for feed.data
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.type
     *
     * @return the value of feed.type
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.type
     *
     * @param type the value for feed.type
     *
     * @mbg.generated Thu Aug 01 16:32:27 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }
}